export const testCases = [
  {
    "Test Case ID":"IOS-PRO-00001",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Approve iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00002",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00003",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Escalate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00004",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Escalate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00005",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Archive iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00006",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Reject iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00007",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00008",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Archive iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00009",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Archive iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00010",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00011",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Archive iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00012",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Edit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00013",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Validate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00014",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00015",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Update iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00016",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00017",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Validate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00018",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Restore iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00019",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Validate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00020",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Restore iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00021",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Clone iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00022",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Validate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00023",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Approve iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00024",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Search iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00025",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Escalate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00026",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Archive iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00027",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Update iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00028",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Escalate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00029",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Clone iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00030",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Search iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00031",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00032",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Route iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00033",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Approve iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00034",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Reject iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00035",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Reject iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00036",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Delete iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00037",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Validate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00038",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Edit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00039",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Search iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00040",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Escalate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00041",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Update iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00042",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Approve iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00043",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Escalate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00044",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Route iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00045",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Delete iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00046",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Approve iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00047",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00048",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00049",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00050",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Route iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00051",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Reject iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00052",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Validate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00053",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Approve iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00054",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Delete iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00055",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Restore iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00056",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00057",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Reject iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00058",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00059",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Edit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00060",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Archive iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00061",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00062",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Route iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00063",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Restore iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00064",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Restore iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00065",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Edit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00066",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Restore iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00067",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Approve iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00068",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00069",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00070",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Validate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00071",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Edit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00072",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Escalate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00073",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00074",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00075",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Approve iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00076",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Delete iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00077",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Route iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00078",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Delete iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00079",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Clone iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00080",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Delete iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00081",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Restore iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00082",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Delete iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00083",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Restore iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00084",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00085",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Clone iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00086",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Edit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00087",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Search iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00088",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Validate iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00089",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00090",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Edit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00091",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Approve iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00092",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Reject iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00093",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Archive iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00094",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Route iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00095",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00096",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Edit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00097",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00098",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Reject iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00099",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Submit iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-PRO-00100",
    "Product":"iOS",
    "Folder":"profile",
    "Capability":"profile",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Create iOS profile",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open profile.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  }
];