export const testCases = [
  {
    "Test Case ID":"WEB-API-00001",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00002",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Archive WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00003",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Restore WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00004",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Approve WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00005",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Escalate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00006",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Update WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00007",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Edit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00008",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Restore WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00009",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Approve WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00010",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00011",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Route WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00012",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Update WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00013",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Validate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00014",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Restore WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00015",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Archive WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00016",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Route WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00017",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00018",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Validate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00019",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Route WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00020",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00021",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Route WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00022",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Edit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00023",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00024",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Approve WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00025",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Edit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00026",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Validate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00027",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00028",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Clone WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00029",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Restore WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00030",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Archive WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00031",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Restore WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00032",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Archive WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00033",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Edit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00034",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00035",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Route WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00036",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Create WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00037",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Archive WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00038",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Create WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00039",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00040",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Clone WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00041",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00042",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Clone WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00043",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00044",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00045",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Validate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00046",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Route WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00047",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Reject WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00048",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00049",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Create WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00050",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00051",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Clone WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00052",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00053",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00054",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00055",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Escalate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00056",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Restore WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00057",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Escalate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00058",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Route WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00059",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Reject WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00060",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00061",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00062",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00063",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Update WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00064",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Escalate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00065",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00066",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00067",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Reject WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00068",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Clone WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00069",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Restore WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00070",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00071",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Approve WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00072",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00073",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00074",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00075",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Edit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00076",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00077",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00078",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00079",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Update WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00080",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Approve WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00081",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Update WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00082",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00083",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00084",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Edit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00085",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00086",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00087",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Approve WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00088",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00089",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Archive WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00090",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Create WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00091",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00092",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Clone WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00093",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Validate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00094",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Create WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00095",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Reject WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00096",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Validate WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00097",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00098",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Archive WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00099",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00100",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Submit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00101",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Archive WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00102",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Approve WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00103",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Route WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00104",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Edit WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00105",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Clone WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00106",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00107",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Restore WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00108",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00109",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Reject WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-API-00110",
    "Product":"WebApps",
    "Folder":"api",
    "Capability":"api",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Search WebApps api",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open api.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  }
];