export const testCases = [
  {
    "Test Case ID":"IOS-ONB-00001",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Route iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00002",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Escalate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00003",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00004",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Archive iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00005",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Approve iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00006",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00007",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Approve iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00008",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00009",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00010",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Clone iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00011",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00012",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Route iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00013",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Create iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00014",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00015",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Validate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00016",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00017",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00018",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Route iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00019",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Search iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00020",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Create iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00021",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Clone iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00022",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Validate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00023",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Clone iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00024",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Reject iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00025",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Clone iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00026",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00027",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Clone iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00028",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Clone iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00029",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00030",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00031",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Create iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00032",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Delete iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00033",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00034",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Reject iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00035",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Escalate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00036",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00037",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00038",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00039",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00040",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Clone iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00041",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Search iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00042",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00043",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00044",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00045",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Search iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00046",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Escalate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00047",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Delete iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00048",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00049",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Archive iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00050",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Validate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00051",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Route iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00052",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00053",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00054",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Reject iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00055",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00056",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Validate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00057",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Create iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00058",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Validate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00059",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Validate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00060",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Delete iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00061",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Validate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00062",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Reject iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00063",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Search iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00064",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00065",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Clone iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00066",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Create iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00067",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00068",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00069",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00070",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00071",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Search iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00072",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00073",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00074",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Escalate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00075",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00076",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Route iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00077",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Validate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00078",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Approve iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00079",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Submit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00080",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Route iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00081",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Delete iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00082",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Delete iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00083",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Archive iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00084",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Create iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00085",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Submit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00086",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Create iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00087",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Restore iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00088",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Escalate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00089",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Reject iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00090",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Submit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00091",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Escalate iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00092",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Clone iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00093",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Reject iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00094",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Update iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00095",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Archive iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00096",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Delete iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00097",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Approve iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00098",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Submit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00099",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Create iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-ONB-00100",
    "Product":"iOS",
    "Folder":"onboarding",
    "Capability":"onboarding",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Edit iOS onboarding",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open onboarding.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  }
];