export const testCases = [
  {
    "Test Case ID":"AWS-SEC-00001",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Edit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00002",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Approve AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00003",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Escalate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00004",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Search AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00005",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Restore AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00006",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Delete AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00007",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Approve AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00008",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Clone AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00009",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Edit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00010",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Approve AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00011",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00012",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Delete AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00013",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Clone AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00014",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Validate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00015",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Clone AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00016",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Clone AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00017",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Archive AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00018",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Approve AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00019",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Update AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00020",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Validate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00021",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Submit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00022",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Escalate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00023",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Route AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00024",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00025",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00026",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00027",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00028",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Validate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00029",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Update AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00030",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Edit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00031",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00032",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Reject AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00033",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Update AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00034",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Route AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00035",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Update AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00036",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00037",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Archive AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00038",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Clone AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00039",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Escalate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00040",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Approve AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00041",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00042",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Reject AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00043",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Archive AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00044",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Edit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00045",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Route AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00046",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Reject AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00047",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Escalate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00048",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Clone AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00049",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Delete AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00050",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Submit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00051",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Delete AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00052",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Restore AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00053",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00054",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Submit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00055",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Submit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00056",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Clone AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00057",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Submit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00058",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Clone AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00059",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Approve AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00060",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Delete AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00061",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Validate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00062",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Escalate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00063",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Restore AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00064",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Escalate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00065",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Validate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00066",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Delete AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00067",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Update AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00068",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00069",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Edit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00070",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Search AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00071",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Reject AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00072",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Route AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00073",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Validate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00074",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Clone AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00075",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Route AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00076",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Edit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00077",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Edit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00078",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00079",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Reject AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00080",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Delete AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00081",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00082",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Edit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00083",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Edit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00084",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Submit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00085",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Validate AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00086",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Reject AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00087",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Submit AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00088",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Delete AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00089",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-SEC-00090",
    "Product":"AWS",
    "Folder":"security",
    "Capability":"security",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Update AWS security",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open security.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  }
];