export const testCases = [
  {
    "Test Case ID":"AWS-COS-00001",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Clone AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00002",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Edit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00003",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Search AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00004",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00005",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00006",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Route AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00007",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Approve AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00008",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00009",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Approve AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00010",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Delete AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00011",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Clone AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00012",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00013",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Delete AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00014",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Validate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00015",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Restore AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00016",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00017",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00018",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Validate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00019",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Update AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00020",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Edit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00021",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Delete AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00022",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00023",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Clone AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00024",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Validate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00025",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Restore AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00026",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00027",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00028",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Delete AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00029",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00030",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00031",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Route AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00032",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Submit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00033",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Delete AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00034",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Submit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00035",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00036",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Escalate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00037",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Escalate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00038",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Route AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00039",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Approve AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00040",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Reject AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00041",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Restore AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00042",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Clone AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00043",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Approve AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00044",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Restore AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00045",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Reject AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00046",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Clone AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00047",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Restore AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00048",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Reject AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00049",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Delete AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00050",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00051",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Escalate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00052",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Clone AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00053",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Validate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00054",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00055",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00056",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Submit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00057",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Escalate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00058",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00059",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Delete AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00060",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00061",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Clone AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00062",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Escalate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00063",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Search AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00064",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Escalate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00065",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Search AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00066",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Search AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00067",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Update AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00068",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Restore AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00069",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00070",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00071",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Submit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00072",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Search AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00073",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Approve AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00074",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00075",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Reject AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00076",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Route AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00077",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Delete AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00078",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Validate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00079",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00080",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Delete AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00081",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00082",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Validate AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00083",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Search AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00084",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Submit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00085",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Archive AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00086",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Submit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00087",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Create AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00088",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Submit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00089",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Clone AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-COS-00090",
    "Product":"AWS",
    "Folder":"cost",
    "Capability":"cost",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Edit AWS cost",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open cost.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  }
];