export const testCases = [
  {
    "Test Case ID":"AWS-EC2-00001",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Escalate AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00002",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Archive AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00003",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Create AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00004",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Delete AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00005",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Clone AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00006",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Update AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00007",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Update AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00008",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Delete AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00009",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Clone AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00010",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Archive AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00011",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Search AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00012",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Validate AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00013",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Approve AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00014",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Route AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00015",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00016",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Delete AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00017",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Submit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00018",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Clone AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00019",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Submit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00020",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Create AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00021",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00022",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Approve AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00023",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Restore AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00024",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Escalate AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00025",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Route AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00026",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Archive AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00027",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Edit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00028",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Search AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00029",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00030",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Clone AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00031",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Clone AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00032",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00033",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Route AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00034",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Archive AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00035",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Archive AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00036",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00037",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Restore AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00038",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Approve AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00039",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Search AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00040",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Route AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00041",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Update AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00042",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Clone AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00043",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Update AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00044",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Validate AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00045",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Edit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00046",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00047",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Create AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00048",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Update AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00049",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Update AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00050",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Route AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00051",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Restore AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00052",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Delete AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00053",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Escalate AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00054",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Edit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00055",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Edit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00056",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Archive AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00057",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Edit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00058",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Search AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00059",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Archive AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00060",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Search AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00061",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Update AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00062",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Restore AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00063",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Escalate AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00064",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Validate AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00065",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Validate AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00066",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Archive AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00067",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Create AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00068",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Create AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00069",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00070",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00071",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Edit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00072",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00073",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Approve AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00074",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Approve AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00075",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Route AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00076",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Route AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00077",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Create AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00078",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Archive AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00079",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Create AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00080",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Restore AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00081",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Clone AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00082",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Validate AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00083",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Approve AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00084",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Restore AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00085",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Approve AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00086",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Create AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00087",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Edit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00088",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Reject AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00089",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Submit AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-EC2-00090",
    "Product":"AWS",
    "Folder":"ec2",
    "Capability":"ec2",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Route AWS ec2",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open ec2.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  }
];