export const testCases = [
  {
    "Test Case ID":"AWS-LAM-00001",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Escalate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00002",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Route AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00003",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Escalate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00004",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00005",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00006",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Search AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00007",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Validate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00008",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00009",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Create AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00010",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Submit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00011",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Search AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00012",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Approve AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00013",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Clone AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00014",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Delete AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00015",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Search AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00016",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Edit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00017",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Clone AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00018",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00019",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Approve AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00020",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Restore AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00021",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Route AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00022",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00023",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Archive AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00024",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Route AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00025",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Create AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00026",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Submit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00027",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Clone AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00028",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Search AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00029",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Submit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00030",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Validate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00031",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Create AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00032",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Approve AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00033",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Validate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00034",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00035",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Edit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00036",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Archive AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00037",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Delete AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00038",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Restore AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00039",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Submit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00040",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00041",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Clone AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00042",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Edit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00043",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Reject AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00044",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Delete AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00045",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00046",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Restore AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00047",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Clone AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00048",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00049",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Approve AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00050",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Search AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00051",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Submit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00052",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Validate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00053",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Approve AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00054",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Approve AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00055",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Route AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00056",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Archive AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00057",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Clone AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00058",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Submit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00059",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Create AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00060",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Escalate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00061",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Reject AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00062",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Create AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00063",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Validate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00064",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Delete AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00065",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Route AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00066",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00067",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Validate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00068",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Route AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00069",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Route AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00070",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Create AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00071",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Validate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00072",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Delete AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00073",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Submit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00074",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00075",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Route AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00076",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Edit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00077",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Edit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00078",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00079",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Validate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00080",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Submit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00081",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Edit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00082",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Edit AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00083",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Route AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00084",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Escalate AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00085",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Restore AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00086",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Approve AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00087",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00088",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Delete AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00089",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Create AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-LAM-00090",
    "Product":"AWS",
    "Folder":"lambda",
    "Capability":"lambda",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Update AWS lambda",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open lambda.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  }
];