export const testCases = [
  {
    "Test Case ID":"API-CON-00001",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Create API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00002",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Performance",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00003",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Security",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00004",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Restore API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00005",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Route API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00006",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Archive API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00007",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00008",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00009",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Security",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00010",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00011",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Functional",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00012",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Functional",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00013",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Accessibility",
    "Scenario":"Route API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00014",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Accessibility",
    "Scenario":"Archive API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00015",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Integration",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00016",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Edit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00017",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Performance",
    "Scenario":"Route API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00018",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Clone API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00019",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00020",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Integration",
    "Scenario":"Archive API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00021",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00022",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Search API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00023",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00024",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Security",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00025",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00026",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Integration",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00027",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Functional",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00028",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00029",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Route API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00030",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Clone API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00031",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Functional",
    "Scenario":"Create API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00032",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Performance",
    "Scenario":"Route API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00033",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00034",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"UI",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00035",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Performance",
    "Scenario":"Delete API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00036",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Security",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00037",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00038",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Performance",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00039",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Archive API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00040",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00041",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Security",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00042",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Performance",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00043",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Create API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00044",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"UI",
    "Scenario":"Archive API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00045",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00046",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Security",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00047",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Edit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00048",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00049",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Restore API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00050",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Performance",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00051",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Edit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00052",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Edit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00053",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Performance",
    "Scenario":"Create API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00054",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00055",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Security",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00056",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Integration",
    "Scenario":"Search API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00057",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00058",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Performance",
    "Scenario":"Edit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00059",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00060",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Functional",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00061",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00062",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Performance",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00063",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Performance",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00064",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Route API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00065",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Performance",
    "Scenario":"Create API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00066",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00067",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Functional",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00068",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Security",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00069",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Delete API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00070",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Integration",
    "Scenario":"Restore API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00071",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00072",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Update API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00073",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00074",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Functional",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00075",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Performance",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00076",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Accessibility",
    "Scenario":"Delete API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00077",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Edit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00078",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Integration",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00079",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00080",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00081",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Integration",
    "Scenario":"Search API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00082",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00083",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00084",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Accessibility",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00085",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Validate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00086",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Route API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00087",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Performance",
    "Scenario":"Route API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00088",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Clone API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00089",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Update API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00090",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00091",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Escalate API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00092",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"UI",
    "Scenario":"Restore API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00093",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Security",
    "Scenario":"Delete API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00094",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Archive API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00095",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Clone API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00096",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Clone API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00097",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Accessibility",
    "Scenario":"Edit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00098",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Route API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00099",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Security",
    "Scenario":"Archive API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00100",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"UI",
    "Scenario":"Create API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00101",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00102",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Archive API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00103",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Clone API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00104",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Integration",
    "Scenario":"Restore API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00105",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Search API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00106",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Regression",
    "Scenario":"Update API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00107",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Integration",
    "Scenario":"Update API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00108",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Update API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00109",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"UI",
    "Scenario":"Approve API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00110",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Clone API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00111",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Regression",
    "Scenario":"Reject API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00112",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Archive API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00113",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Restore API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00114",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Integration",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00115",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Regression",
    "Scenario":"Clone API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00116",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Edit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00117",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Functional",
    "Scenario":"Create API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00118",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Search API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00119",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Submit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-CON-00120",
    "Product":"API",
    "Folder":"contract",
    "Capability":"contract",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Security",
    "Scenario":"Edit API contract",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open contract.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  }
];