export const testCases = [
  {
    "Test Case ID":"TOP-SAL-00001",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Submit TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00002",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Escalate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00003",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Search TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00004",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Submit TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00005",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00006",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00007",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Clone TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00008",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Archive TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00009",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00010",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00011",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00012",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Create TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00013",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Clone TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00014",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Reject TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00015",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00016",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00017",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Approve TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00018",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Restore TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00019",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Create TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00020",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Clone TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00021",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Approve TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00022",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Reject TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00023",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Delete TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00024",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Reject TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00025",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Restore TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00026",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Route TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00027",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Delete TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00028",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Clone TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00029",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Escalate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00030",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Approve TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00031",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Escalate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00032",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Search TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00033",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Update TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00034",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Escalate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00035",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Submit TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00036",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Clone TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00037",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00038",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Approve TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00039",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00040",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Route TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00041",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Archive TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00042",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Submit TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00043",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00044",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Create TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00045",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Search TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00046",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Restore TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00047",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Route TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00048",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Search TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00049",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Delete TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00050",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Create TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00051",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Route TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00052",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Archive TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00053",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Submit TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00054",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Approve TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00055",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Route TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00056",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Update TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00057",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Update TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00058",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Update TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00059",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Delete TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00060",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00061",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Delete TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00062",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Escalate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00063",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Clone TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00064",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Route TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00065",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Clone TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00066",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Search TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00067",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Reject TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00068",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Search TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00069",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Submit TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00070",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Create TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00071",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Restore TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00072",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Search TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00073",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Delete TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00074",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Archive TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00075",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Validate TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00076",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Search TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00077",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Create TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00078",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Edit TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00079",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Submit TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SAL-00080",
    "Product":"TopProducts",
    "Folder":"salesforce",
    "Capability":"salesforce",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Update TopProducts salesforce",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open salesforce.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  }
];