export const testCases = [
  {
    "Test Case ID":"AZU-STO-00001",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Route Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00002",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Clone Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00003",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Validate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00004",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Edit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00005",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Submit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00006",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Approve Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00007",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00008",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Clone Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00009",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Clone Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00010",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Approve Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00011",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Search Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00012",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Create Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00013",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Validate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00014",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Reject Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00015",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Search Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00016",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Clone Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00017",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Delete Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00018",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Escalate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00019",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Approve Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00020",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Route Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00021",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Route Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00022",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Reject Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00023",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Search Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00024",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Restore Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00025",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Escalate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00026",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00027",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Restore Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00028",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Edit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00029",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Delete Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00030",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Escalate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00031",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00032",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Submit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00033",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Route Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00034",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Route Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00035",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Reject Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00036",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Reject Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00037",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Route Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00038",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Escalate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00039",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Reject Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00040",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Archive Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00041",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Edit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00042",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Archive Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00043",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Escalate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00044",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Create Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00045",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Delete Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00046",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Search Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00047",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Restore Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00048",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Delete Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00049",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Clone Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00050",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Edit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00051",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Approve Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00052",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Create Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00053",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Clone Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00054",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Validate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00055",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Edit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00056",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Escalate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00057",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Validate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00058",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Edit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00059",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Edit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00060",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Create Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00061",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Create Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00062",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Validate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00063",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Create Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00064",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Submit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00065",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Submit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00066",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Delete Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00067",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Create Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00068",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Escalate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00069",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Escalate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00070",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Reject Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00071",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Search Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00072",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Submit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00073",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Validate Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00074",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Edit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00075",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Clone Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00076",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Archive Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00077",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Search Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00078",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Search Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00079",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Archive Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00080",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Approve Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00081",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Update Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00082",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Restore Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00083",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Restore Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00084",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Reject Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00085",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00086",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Search Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00087",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Search Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00088",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Approve Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00089",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Edit Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-STO-00090",
    "Product":"Azure",
    "Folder":"storage",
    "Capability":"storage",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Update Azure storage",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open storage.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  }
];