export const testCases = [
  {
    "Test Case ID":"IOS-LOG-00001",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Update iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00002",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Validate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00003",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Clone iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00004",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Clone iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00005",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00006",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Route iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00007",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00008",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00009",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00010",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Delete iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00011",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Create iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00012",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Reject iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00013",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00014",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Delete iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00015",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Submit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00016",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Edit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00017",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00018",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Create iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00019",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Delete iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00020",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Route iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00021",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Validate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00022",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Restore iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00023",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00024",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Archive iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00025",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Validate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00026",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Edit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00027",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Update iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00028",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Escalate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00029",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Submit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00030",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Route iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00031",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Submit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00032",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Restore iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00033",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Route iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00034",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Clone iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00035",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00036",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Create iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00037",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Update iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00038",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Update iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00039",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Route iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00040",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Escalate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00041",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Escalate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00042",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Restore iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00043",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Validate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00044",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Create iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00045",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Submit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00046",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Delete iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00047",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00048",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Reject iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00049",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Delete iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00050",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Edit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00051",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Validate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00052",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Create iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00053",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Reject iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00054",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Create iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00055",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Escalate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00056",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Submit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00057",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00058",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Create iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00059",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Escalate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00060",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00061",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Restore iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00062",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Restore iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00063",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00064",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Reject iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00065",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Delete iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00066",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Reject iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00067",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Edit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00068",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00069",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Archive iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00070",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Submit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00071",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00072",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00073",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Validate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00074",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00075",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Search iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00076",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Archive iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00077",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Delete iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00078",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Edit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00079",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00080",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Edit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00081",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Archive iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00082",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Edit iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00083",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Restore iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00084",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Archive iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00085",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Escalate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00086",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Clone iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00087",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00088",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Reject iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00089",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Update iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00090",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Update iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00091",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Approve iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00092",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Validate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00093",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Escalate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00094",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Escalate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00095",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Route iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00096",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Reject iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00097",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Escalate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00098",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Create iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00099",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Create iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  },
  {
    "Test Case ID":"IOS-LOG-00100",
    "Product":"iOS",
    "Folder":"login",
    "Capability":"login",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Validate iOS login",
    "Preconditions":"iOS access and test data available",
    "Steps":"1. Open login.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"iPhone 15\", \"os\": \"iOS 18\", \"network\": \"Wi-Fi\"}"
  }
];