export const testCases = [
  {
    "Test Case ID":"AND-OFF-00001",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00002",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Approve Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00003",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Approve Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00004",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Reject Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00005",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Submit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00006",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Restore Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00007",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Route Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00008",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Archive Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00009",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00010",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Approve Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00011",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Restore Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00012",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Restore Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00013",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Escalate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00014",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Submit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00015",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Escalate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00016",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Approve Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00017",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00018",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00019",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Reject Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00020",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00021",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00022",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Archive Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00023",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Approve Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00024",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Reject Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00025",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00026",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Clone Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00027",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Create Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00028",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Submit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00029",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Clone Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00030",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00031",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Edit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00032",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00033",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Search Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00034",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Edit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00035",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Edit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00036",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Route Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00037",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Route Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00038",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00039",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00040",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Clone Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00041",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Create Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00042",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Restore Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00043",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Search Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00044",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Approve Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00045",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Clone Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00046",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Archive Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00047",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Escalate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00048",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00049",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Delete Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00050",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Search Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00051",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Escalate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00052",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Restore Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00053",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Submit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00054",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Delete Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00055",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Edit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00056",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Delete Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00057",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Reject Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00058",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Clone Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00059",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00060",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Escalate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00061",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00062",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Escalate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00063",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00064",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Search Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00065",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Route Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00066",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Archive Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00067",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Edit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00068",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Approve Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00069",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Delete Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00070",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Escalate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00071",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00072",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Search Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00073",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Approve Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00074",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Create Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00075",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00076",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00077",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Route Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00078",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Submit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00079",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Create Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00080",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Create Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00081",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00082",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Archive Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00083",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Approve Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00084",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00085",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Search Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00086",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00087",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Submit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00088",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Update Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00089",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Validate Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00090",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Clone Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00091",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Reject Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00092",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Restore Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00093",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Submit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00094",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Submit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00095",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Reject Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00096",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Route Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00097",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Edit Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00098",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Archive Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00099",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Search Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-OFF-00100",
    "Product":"Android",
    "Folder":"offline",
    "Capability":"offline",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Archive Android offline",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open offline.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  }
];