export const testCases = [
  {
    "Test Case ID":"TOP-SER-00001",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Edit TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00002",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Edit TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00003",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Create TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00004",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Delete TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00005",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Search TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00006",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Validate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00007",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Clone TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00008",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Validate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00009",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Update TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00010",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Archive TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00011",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Create TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00012",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00013",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Search TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00014",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Route TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00015",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00016",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Update TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00017",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00018",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Reject TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00019",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00020",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00021",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00022",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00023",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Create TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00024",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Delete TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00025",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00026",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Escalate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00027",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00028",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Clone TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00029",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Clone TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00030",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Escalate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00031",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Validate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00032",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00033",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00034",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Archive TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00035",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Archive TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00036",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Clone TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00037",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Submit TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00038",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Search TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00039",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00040",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Reject TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00041",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Search TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00042",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Reject TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00043",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Archive TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00044",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00045",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Archive TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00046",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Search TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00047",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Create TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00048",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00049",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Validate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00050",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Route TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00051",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Clone TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00052",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Delete TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00053",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Delete TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00054",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Clone TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00055",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00056",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Edit TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00057",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Delete TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00058",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Edit TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00059",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Edit TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00060",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Validate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00061",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Validate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00062",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00063",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00064",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Update TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00065",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00066",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Validate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00067",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Escalate TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00068",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Search TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00069",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Search TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00070",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Approve TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00071",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Archive TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00072",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00073",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Submit TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00074",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Submit TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00075",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Clone TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00076",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Create TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00077",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Clone TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00078",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Update TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00079",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Restore TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-SER-00080",
    "Product":"TopProducts",
    "Folder":"servicenow",
    "Capability":"servicenow",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Edit TopProducts servicenow",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open servicenow.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  }
];