export const testCases = [
  {
    "Test Case ID":"GCP-IAM-00001",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Delete GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00002",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00003",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Submit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00004",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00005",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Delete GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00006",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Submit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00007",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Delete GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00008",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Validate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00009",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Approve GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00010",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Clone GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00011",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00012",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Delete GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00013",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Delete GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00014",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Route GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00015",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Create GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00016",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00017",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Delete GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00018",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Create GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00019",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Search GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00020",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Clone GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00021",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Edit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00022",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Submit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00023",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Create GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00024",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Create GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00025",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Restore GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00026",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Validate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00027",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00028",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00029",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Archive GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00030",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00031",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00032",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Restore GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00033",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Archive GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00034",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Restore GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00035",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Archive GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00036",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Reject GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00037",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Reject GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00038",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Edit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00039",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Submit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00040",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Edit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00041",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Clone GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00042",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00043",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Reject GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00044",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00045",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Search GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00046",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Reject GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00047",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Create GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00048",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Approve GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00049",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00050",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00051",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Search GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00052",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Archive GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00053",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Approve GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00054",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Submit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00055",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00056",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Edit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00057",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Approve GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00058",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Validate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00059",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Clone GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00060",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Restore GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00061",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Approve GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00062",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Submit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00063",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Archive GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00064",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00065",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Create GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00066",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Clone GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00067",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00068",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00069",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Validate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00070",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Validate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00071",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Reject GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00072",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Submit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00073",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00074",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00075",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Archive GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00076",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00077",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Approve GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00078",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Escalate GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00079",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Submit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00080",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Route GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00081",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Reject GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00082",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Route GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00083",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00084",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Update GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00085",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Route GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00086",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Delete GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00087",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Create GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00088",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Delete GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00089",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Edit GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-IAM-00090",
    "Product":"GCP",
    "Folder":"iam",
    "Capability":"iam",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Search GCP iam",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open iam.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  }
];