export const testCases = [
  {
    "Test Case ID":"GCP-BIG-00001",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Submit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00002",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Approve GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00003",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Search GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00004",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Edit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00005",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Approve GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00006",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Update GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00007",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Escalate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00008",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Clone GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00009",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Search GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00010",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Update GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00011",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00012",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Validate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00013",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Clone GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00014",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Approve GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00015",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Validate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00016",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Edit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00017",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Validate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00018",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00019",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Clone GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00020",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Edit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00021",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00022",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Create GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00023",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00024",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00025",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Edit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00026",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Search GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00027",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Clone GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00028",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Archive GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00029",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Submit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00030",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Approve GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00031",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Archive GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00032",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Delete GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00033",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Submit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00034",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Validate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00035",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Edit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00036",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00037",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Update GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00038",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Clone GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00039",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Escalate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00040",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Approve GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00041",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Update GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00042",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Escalate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00043",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00044",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Edit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00045",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Delete GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00046",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Reject GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00047",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00048",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00049",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Reject GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00050",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Archive GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00051",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Archive GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00052",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Archive GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00053",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Reject GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00054",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Submit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00055",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Escalate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00056",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Validate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00057",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00058",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Validate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00059",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Update GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00060",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Restore GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00061",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Create GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00062",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Escalate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00063",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Validate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00064",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00065",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Escalate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00066",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Submit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00067",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Approve GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00068",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Submit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00069",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Escalate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00070",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Reject GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00071",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Create GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00072",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Escalate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00073",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Approve GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00074",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Create GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00075",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00076",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Escalate GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00077",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Update GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00078",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Archive GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00079",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00080",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Submit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00081",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Delete GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00082",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Submit GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00083",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00084",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00085",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Route GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00086",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Delete GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00087",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Approve GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00088",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Update GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00089",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Restore GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"GCP-BIG-00090",
    "Product":"GCP",
    "Folder":"bigquery",
    "Capability":"bigquery",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Clone GCP bigquery",
    "Preconditions":"GCP access and test data available",
    "Steps":"1. Open bigquery.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"GCS\", \"region\": \"us-central1\", \"iam_role\": \"Tester\"}"
  }
];