export const testCases = [
  {
    "Test Case ID":"API-AUT-00001",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Functional",
    "Scenario":"Delete API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00002",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Integration",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00003",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Functional",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00004",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Integration",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00005",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Update API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00006",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Performance",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00007",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Submit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00008",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00009",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Create API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00010",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Approve API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00011",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Integration",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00012",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Performance",
    "Scenario":"Approve API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00013",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Archive API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00014",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Performance",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00015",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"UI",
    "Scenario":"Validate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00016",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00017",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Approve API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00018",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Security",
    "Scenario":"Update API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00019",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00020",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Escalate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00021",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Performance",
    "Scenario":"Archive API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00022",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Submit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00023",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"UI",
    "Scenario":"Escalate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00024",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Escalate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00025",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Integration",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00026",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Functional",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00027",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Accessibility",
    "Scenario":"Update API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00028",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Functional",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00029",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Regression",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00030",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Functional",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00031",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Accessibility",
    "Scenario":"Approve API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00032",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00033",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Performance",
    "Scenario":"Delete API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00034",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Functional",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00035",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Search API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00036",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Functional",
    "Scenario":"Approve API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00037",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Submit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00038",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00039",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Security",
    "Scenario":"Create API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00040",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Integration",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00041",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Integration",
    "Scenario":"Update API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00042",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Performance",
    "Scenario":"Submit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00043",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Security",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00044",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Validate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00045",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Regression",
    "Scenario":"Escalate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00046",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Functional",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00047",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Security",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00048",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00049",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Validate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00050",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Performance",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00051",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Functional",
    "Scenario":"Archive API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00052",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Delete API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00053",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"UI",
    "Scenario":"Submit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00054",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00055",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Delete API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00056",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Functional",
    "Scenario":"Escalate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00057",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Functional",
    "Scenario":"Create API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00058",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Functional",
    "Scenario":"Update API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00059",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Performance",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00060",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Security",
    "Scenario":"Archive API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00061",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Security",
    "Scenario":"Search API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00062",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Accessibility",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00063",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Integration",
    "Scenario":"Submit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00064",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Regression",
    "Scenario":"Archive API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00065",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Regression",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00066",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Integration",
    "Scenario":"Validate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00067",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Security",
    "Scenario":"Submit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00068",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Functional",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00069",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Validate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00070",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00071",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Security",
    "Scenario":"Create API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00072",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Integration",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00073",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00074",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Performance",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00075",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Performance",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00076",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Regression",
    "Scenario":"Escalate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00077",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Integration",
    "Scenario":"Delete API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00078",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Functional",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00079",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Performance",
    "Scenario":"Search API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00080",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Archive API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00081",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Regression",
    "Scenario":"Approve API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00082",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Archive API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00083",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Functional",
    "Scenario":"Escalate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00084",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Accessibility",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00085",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Performance",
    "Scenario":"Delete API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00086",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Escalate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00087",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Regression",
    "Scenario":"Escalate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00088",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Integration",
    "Scenario":"Validate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00089",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Search API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00090",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"UI",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00091",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Accessibility",
    "Scenario":"Update API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00092",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Performance",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00093",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Performance",
    "Scenario":"Update API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00094",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Regression",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00095",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Performance",
    "Scenario":"Submit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00096",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00097",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Functional",
    "Scenario":"Delete API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00098",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Security",
    "Scenario":"Approve API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00099",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Regression",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00100",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Security",
    "Scenario":"Edit API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00101",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Performance",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00102",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Performance",
    "Scenario":"Archive API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00103",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Integration",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00104",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Accessibility",
    "Scenario":"Update API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00105",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Security",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00106",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Accessibility",
    "Scenario":"Search API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00107",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00108",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00109",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Integration",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00110",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Security",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00111",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"Regression",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00112",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Restore API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00113",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"UI",
    "Scenario":"Approve API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00114",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Create -> Validate -> Respond",
    "Test Type":"Accessibility",
    "Scenario":"Validate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00115",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"B2B API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"UI",
    "Scenario":"Clone API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00116",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Functional",
    "Scenario":"Update API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00117",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Partner API",
    "Flow":"Auth -> Call -> Verify -> Log",
    "Test Type":"Accessibility",
    "Scenario":"Route API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00118",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Public API",
    "Flow":"Schema -> Contract -> Deploy -> Monitor",
    "Test Type":"UI",
    "Scenario":"Delete API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00119",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Integration",
    "Scenario":"Validate API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  },
  {
    "Test Case ID":"API-AUT-00120",
    "Product":"API",
    "Folder":"auth",
    "Capability":"auth",
    "Domain":"Internal API",
    "Flow":"Sync -> Retry -> Recover",
    "Test Type":"Regression",
    "Scenario":"Reject API auth",
    "Preconditions":"API access and test data available",
    "Steps":"1. Open auth.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"method\": \"GET\", \"endpoint\": \"\/v1\/items\", \"auth\": \"OAuth2\", \"payload\": \"{}\"}"
  }
];