export const testCases = [
  {
    "Test Case ID":"TOP-WOR-00001",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Archive TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00002",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Archive TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00003",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Restore TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00004",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Route TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00005",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Submit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00006",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Approve TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00007",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Submit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00008",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Edit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00009",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Submit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00010",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00011",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Edit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00012",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00013",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Archive TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00014",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00015",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00016",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Clone TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00017",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Restore TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00018",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Approve TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00019",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Edit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00020",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Submit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00021",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Route TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00022",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Approve TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00023",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Route TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00024",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00025",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00026",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Validate TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00027",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Restore TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00028",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Delete TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00029",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Create TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00030",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00031",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Update TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00032",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Approve TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00033",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00034",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00035",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Submit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00036",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Search TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00037",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Create TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00038",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Create TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00039",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Search TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00040",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Submit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00041",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Escalate TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00042",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Search TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00043",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Edit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00044",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Update TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00045",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Archive TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00046",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Archive TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00047",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Clone TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00048",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Restore TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00049",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Archive TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00050",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Update TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00051",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Delete TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00052",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Clone TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00053",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Approve TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00054",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00055",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Clone TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00056",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Restore TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00057",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Create TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00058",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00059",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Restore TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00060",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00061",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Approve TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00062",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Approve TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00063",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Clone TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00064",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Validate TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00065",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Escalate TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00066",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Delete TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00067",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Search TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00068",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Edit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00069",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Escalate TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00070",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Edit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00071",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Delete TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00072",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Reject TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00073",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Update TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00074",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Approve TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00075",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Escalate TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00076",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Escalate TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00077",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Edit TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00078",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Create TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00079",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Create TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-WOR-00080",
    "Product":"TopProducts",
    "Folder":"workday",
    "Capability":"workday",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Delete TopProducts workday",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open workday.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  }
];