import InputPanel from "@/components/generator/InputPanel";
import OutputPanel from "@/components/generator/OutputPanel";
import { useGeneratorStore } from "@/store/generatorStore";
import { templates } from "@/data/templates";

const DEMO_RESULT = {
  title: "Salesforce Lead-to-Opportunity — Playwright TS",
  script: `// TestForge AI — Generated by KR AppSuite
// Salesforce Lead-to-Opportunity Flow
// Framework: Playwright | Lang: TypeScript
// Generated: ${new Date().toISOString().slice(0, 10)}

import { test, expect, type Page } from '@playwright/test';

// ═══════════════════════════════════════════════
// Page Object: LoginPage
// ═══════════════════════════════════════════════
class LoginPage {
  constructor(private page: Page) {}

  async login(username: string, password: string) {
    await this.page.goto(process.env.SF_ORG_URL!);
    await this.page.fill('#username', username);
    await this.page.fill('#password', password);
    await this.page.click('#Login');
    await this.page.waitForURL('**/lightning/**');
  }
}

// ═══════════════════════════════════════════════
// Page Object: LeadPage
// ═══════════════════════════════════════════════
class LeadPage {
  constructor(private page: Page) {}

  async navigate() {
    await this.page.goto('/lightning/o/Lead/list');
    await this.page.waitForSelector('.slds-page-header');
  }

  async createLead(data: Record<string, string>) {
    await this.page.click('button:has-text("New")');
    await this.page.waitForSelector('.modal-container');
    for (const [field, value] of Object.entries(data)) {
      await this.page.fill(\`input[name="\${field}"]\`, value);
    }
    await this.page.click('button:has-text("Save")');
    await this.page.waitForSelector('.slds-notify--toast');
  }
}

// ═══════════════════════════════════════════════
// Test Suite: Lead Creation & Conversion
// ═══════════════════════════════════════════════
test.describe('Salesforce Lead-to-Opportunity Flow', () => {
  let loginPage: LoginPage;
  let leadPage: LeadPage;

  test.beforeEach(async ({ page }) => {
    loginPage = new LoginPage(page);
    leadPage = new LeadPage(page);
    await loginPage.login(
      process.env.SF_USERNAME!,
      process.env.SF_PASSWORD!
    );
  });

  test('TC-001: Create lead with all mandatory fields', async ({ page }) => {
    await leadPage.navigate();
    await leadPage.createLead({
      lastName: 'TestLead_' + Date.now(),
      company: 'Acme Corp',
      email: 'test@acme.com',
    });
    await expect(page.locator('.slds-notify--toast'))
      .toContainText('was created');
  });

  test('TC-002: Convert lead to opportunity', async ({ page }) => {
    await leadPage.navigate();
    await page.click('a[data-refid="recordId"]:first-child');
    await page.click('button:has-text("Convert")');
    await page.waitForSelector('.modal-container');
    await page.click('button:has-text("Convert"):last-child');
    await expect(page.locator('.slds-notify--toast'))
      .toContainText('successfully converted');
  });

  test('TC-003: Verify lead assignment rule fires', async ({ page }) => {
    await leadPage.createLead({
      lastName: 'AssignTest_' + Date.now(),
      company: 'Test Corp',
      leadSource: 'Web',
    });
    const ownerField = page.locator('[data-field="OwnerId"]');
    await expect(ownerField).not.toBeEmpty();
  });

  test('TC-004: Create lead with missing required field', async ({ page }) => {
    await leadPage.navigate();
    await page.click('button:has-text("New")');
    await page.click('button:has-text("Save")');
    await expect(page.locator('.slds-form-element__help'))
      .toBeVisible();
  });

  test('TC-005: Duplicate lead detection', async ({ page }) => {
    const data = {
      lastName: 'DuplicateTest',
      company: 'Dupe Corp',
      email: 'dupe@test.com',
    };
    await leadPage.createLead(data);
    await leadPage.createLead(data);
    await expect(page.locator('.duplicateWarning'))
      .toBeVisible();
  });
});`,
  language: "typescript",
  test_cases: [
    { id: "TC-001", name: "Create lead with all mandatory fields", type: "positive", priority: "P1", description: "Verify lead creation with required fields" },
    { id: "TC-002", name: "Convert lead to opportunity successfully", type: "positive", priority: "P1", description: "Test lead conversion workflow" },
    { id: "TC-003", name: "Lead assignment rule fires correctly", type: "positive", priority: "P1", description: "Verify assignment rules trigger" },
    { id: "TC-004", name: "Create lead with missing required field", type: "negative", priority: "P2", description: "Validation error shown" },
    { id: "TC-005", name: "Duplicate lead detection warning", type: "negative", priority: "P2", description: "Duplicate rules trigger" },
  ],
  prerequisites: [
    "npm install @playwright/test",
    "npx playwright install chromium",
    "Create .env with SF_USERNAME, SF_PASSWORD, SF_ORG_URL",
  ],
  coverage_notes: "WHAT'S COVERED:\n✓ Happy path lead creation\n✓ Lead conversion workflow\n✓ Lead assignment rules\n✓ Field validation\n✓ Duplicate detection\n\nNOT COVERED:\n• Email-to-lead integration\n• Scheduled assignments\n• REST API lead creation",
  known_limitations: [
    "Requires active Salesforce org with admin access",
    "Duplicate detection rules must be configured",
    "Assignment rules must be active",
  ],
};

const Index = () => {
  const store = useGeneratorStore();

  const handleGenerate = async () => {
    if (!store.platform || store.businessCase.trim().length < 10) return;
    store.setIsGenerating(true);
    store.setResult(null);
    store.setProgress(0);
    store.setProgressStep(0);

    // Simulate generation steps
    for (let step = 0; step < 6; step++) {
      await new Promise((r) => setTimeout(r, 600));
      store.setProgressStep(step);
      store.setProgress(Math.min(100, (step + 1) * 17));
    }

    store.setProgress(100);
    await new Promise((r) => setTimeout(r, 300));
    store.setIsGenerating(false);
    store.setResult(DEMO_RESULT);
  };

  const handleSurpriseMe = () => {
    const featured = templates.filter((t) => t.is_featured);
    const pick = featured[Math.floor(Math.random() * featured.length)] || templates[0];
    store.setPlatform(pick.platform as any);
    store.setBusinessCase(pick.business_case_text);
    if (pick.suggested_framework) store.setFramework(pick.suggested_framework);
  };

  return (
    <div className="min-h-[calc(100vh-64px)]">
      <div className="max-w-7xl mx-auto px-4 py-6">
        <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
          {/* Input Panel — 2/5 */}
          <div className="lg:col-span-2">
            <div className="rounded-xl border border-border bg-card p-5">
              <InputPanel onGenerate={handleGenerate} onSurpriseMe={handleSurpriseMe} />
            </div>
          </div>
          {/* Output Panel — 3/5 */}
          <div className="lg:col-span-3">
            <div className="rounded-xl border border-border bg-card p-5 min-h-[500px]">
              <OutputPanel />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Index;
