export const testCases = [
  {
    "Test Case ID":"AWS-S3-00001",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00002",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Submit AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00003",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Route AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00004",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Clone AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00005",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Search AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00006",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Route AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00007",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Clone AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00008",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Route AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00009",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Submit AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00010",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Escalate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00011",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Submit AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00012",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Update AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00013",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Reject AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00014",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Reject AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00015",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Create AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00016",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00017",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00018",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Approve AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00019",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Edit AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00020",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Create AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00021",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Escalate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00022",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00023",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Reject AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00024",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Escalate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00025",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00026",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00027",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Create AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00028",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Create AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00029",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00030",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Search AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00031",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00032",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00033",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00034",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Clone AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00035",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00036",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00037",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Validate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00038",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00039",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Route AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00040",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Approve AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00041",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Edit AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00042",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Edit AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00043",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Search AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00044",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Escalate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00045",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Reject AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00046",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Reject AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00047",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00048",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Update AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00049",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Create AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00050",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00051",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00052",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00053",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Escalate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00054",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00055",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Reject AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00056",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Submit AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00057",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Escalate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00058",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Delete AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00059",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Clone AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00060",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Route AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00061",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Update AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00062",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Reject AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00063",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00064",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Approve AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00065",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00066",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Create AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00067",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Route AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00068",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Approve AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00069",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Create AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00070",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00071",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Escalate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00072",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00073",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Route AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00074",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Validate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00075",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Clone AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00076",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00077",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Approve AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00078",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Reject AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00079",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00080",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Create AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00081",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Reject AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00082",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00083",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Create AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00084",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00085",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00086",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Restore AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00087",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Archive AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00088",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Search AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00089",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Validate AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AWS-S3-00090",
    "Product":"AWS",
    "Folder":"s3",
    "Capability":"s3",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Edit AWS s3",
    "Preconditions":"AWS access and test data available",
    "Steps":"1. Open s3.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"EC2\", \"region\": \"us-east-1\", \"iam_role\": \"Tester\"}"
  }
];