"""Add five synthetic product packs without regenerating existing catalogues."""
from generate_market_product_suites import write_pack


def m(slug, label, tasks):
    return slug, label, tasks.split("|")


PACKS = [
    {"root": "GitHub", "key": "github", "display": "GitHub", "prefix": "GHUB", "accent": "cyan", "modules": [
        m("repos", "Repositories", "create a private repository|clone the selected branch|push a commit to an allowed branch|reject a push to a protected branch|fork a permitted repository|transfer repository ownership with approval|archive a disposable repository|compare two commit revisions|restore a deleted test branch|deny private repository access after membership removal"),
        m("pulls", "Pull Requests", "open a pull request against the intended base|require review before merge|dismiss stale approval after a new commit|block merge on a failed required check|resolve a merge conflict|request a code-owner review|merge using the configured strategy|close a pull request without merging|link a pull request to an issue|deny unauthorized pull request edits"),
        m("actions", "Actions and Releases", "run a workflow on the selected commit|restrict workflow token permissions|redact a synthetic secret from logs|cancel a running workflow|download the matching run artifact|enforce deployment environment approval|retry a failed workflow job|publish a draft test release|verify artifact retention expiry|reject an unapproved deployment branch"),
        m("issues", "Issues and Projects", "create an issue from a template|assign an issue to a permitted member|apply and filter issue labels|move an issue between project statuses|link a sub-issue to its parent|close an issue with a reason|reopen a closed issue|restrict private project visibility|update a milestone due date|preserve issue history after an edit"),
        m("security", "Security and Organization Access", "require organization single sign-on|revoke a fine-grained test token|restrict team repository permissions|block a synthetic secret commit under configured push protection|review a dependency vulnerability alert|apply a repository ruleset|audit an organization role change|deny member privilege escalation|restrict third-party application access|remove a departing member's repository access"),
    ]},
    {"root": "GitLab", "key": "gitlab", "display": "GitLab", "prefix": "GLAB", "accent": "amber", "modules": [
        m("projects", "Projects and Repositories", "create a private project in a group|push to an unprotected test branch|reject a protected branch push|configure repository visibility|fork a permitted project|import a synthetic repository|archive a disposable project|restore a test branch from a commit|compare repository revisions|deny access to another private group"),
        m("merges", "Merge Requests", "open a merge request against the intended target|require the configured approval count|reset approval after a new commit|block merge after a pipeline failure|resolve a discussion before merge|review changed files|merge using the configured strategy|close a merge request without merging|assign a permitted reviewer|deny edits by a revoked member"),
        m("pipelines", "CI/CD Pipelines", "validate a pipeline configuration|run a pipeline for the selected branch|apply runner tags to a job|cancel a running pipeline|retry a failed job|pass an artifact to a downstream job|redact a masked synthetic variable|enforce a protected deployment environment|block an unauthorized manual job|expire an artifact at its configured boundary"),
        m("planning", "Issues and Planning", "create an issue with required fields|assign an issue to a group member|filter issues by label|move an issue on a board|associate an issue with a milestone|link an issue to a merge request|close and reopen an issue|restrict confidential issue visibility|update an issue weight|preserve issue discussion history"),
        m("access", "Group Access and Governance", "assign the intended group role|remove inherited access after group removal|revoke a project access token|enforce single sign-on for group members|audit a group permission change|restrict protected tag creation|deny guest access to protected settings|rotate a runner credential|restrict a deploy token's scope|prevent unauthorized project transfer"),
    ]},
    {"root": "Slack", "key": "slack", "display": "Slack", "prefix": "SLCK", "accent": "rose", "modules": [
        m("channels", "Channels and Membership", "create a public test channel|create a private test channel|invite an authorized member|deny private channel access to a nonmember|rename a channel|update a channel topic|archive a disposable channel|restore an archived channel|leave a channel|restrict external channel invitations"),
        m("messages", "Messages and Threads", "send a message to the intended channel|reply in the correct thread|edit one's own message|delete one's own message|add and remove a reaction|mention a permitted user|schedule a test message|cancel a scheduled message|preserve message ordering after reconnect|reject an oversized message clearly"),
        m("search", "Search and Files", "search messages within an authorized channel|exclude private messages from nonmember search|filter results by sender|filter results by date range|upload a synthetic document|download an authorized file|delete one's own test file|deny a revoked file share|search Unicode content|paginate search results without duplicate entries"),
        m("workflows", "Apps and Workflows", "install an approved test application|deny an application requesting prohibited scopes|trigger a workflow from a test event|validate required workflow inputs|deduplicate a repeated webhook event|handle an API rate limit with bounded retry|revoke an application token|send a notification to its configured channel|restrict workflow editing to its owners|record a failed workflow step"),
        m("access", "Workspace Access and Governance", "invite a synthetic workspace member|deactivate a test member|enforce single sign-on|limit a guest to assigned channels|restrict workspace administration|apply a configured message retention policy|audit an application permission change|revoke an active test session|deny cross-workspace resource access|export permitted audit metadata without secrets"),
    ]},
    {"root": "MicrosoftTeams", "key": "microsoft-teams", "display": "Microsoft Teams", "prefix": "MSTM", "accent": "violet", "modules": [
        m("teams", "Teams and Channels", "create a private test team|create a standard channel|create a private channel|add an authorized team member|remove a team member|restrict private channel membership|rename a channel|archive a disposable team|restore an archived team|deny unauthorized team settings edits"),
        m("chat", "Chat and Collaboration", "send a one-to-one test message|send a group chat message|reply in a channel thread|edit one's own message|delete one's own message|add and remove a reaction|mention an authorized member|share a permitted file link|restrict chat with an external domain|preserve messages after reconnect"),
        m("meetings", "Meetings and Calls", "schedule a test meeting|join a meeting using the intended identity|admit a participant from the lobby|restrict presenter permissions|mute and unmute a participant|share a permitted screen|record a meeting with approved policy|restrict recording access|cancel a scheduled meeting|rejoin after a transient network interruption"),
        m("files", "Files and Applications", "upload a synthetic channel file|co-edit a permitted document|resolve a concurrent document update|deny file access to a nonmember|restore a prior document version|add an approved channel tab|install an approved test application|reject a prohibited application|revoke application permissions|remove a tab without deleting its source document"),
        m("access", "Identity and Meeting Policies", "enforce tenant single sign-on|apply guest access policy|block an unauthorized external domain|restrict team creation by policy|apply meeting recording policy|revoke a test user's session|audit a team membership change|deny access after user deactivation|restrict administrative policy changes|verify retention according to tenant policy"),
    ]},
    {"root": "Confluence", "key": "confluence", "display": "Confluence", "prefix": "CNFL", "accent": "blue", "modules": [
        m("spaces", "Spaces and Navigation", "create a private test space|assign a permitted space administrator|restrict space visibility|update a space homepage|organize a page in the space tree|move a page within a space|archive a disposable space|restore an archived space|browse a permitted space|deny access to a restricted space"),
        m("pages", "Pages and Publishing", "create a draft page|publish a page with a title|edit a published page|restore a prior page version|resolve a concurrent page edit|copy a page with permitted content|move a page with its children|delete a disposable page|restore a page from trash|restrict page editing to assigned users"),
        m("collab", "Comments and Reviews", "comment on a permitted page|reply to a page comment|resolve an inline comment|reopen an inline discussion|mention a permitted collaborator|watch a page for changes|stop watching a page|review page version differences|deny comments on a restricted page|preserve discussion history after a page edit"),
        m("content", "Search and Attachments", "search authorized page content|exclude restricted pages from search|filter search results by space|filter pages by label|upload a synthetic attachment|download an authorized attachment|replace an attachment with a new version|restore a prior attachment version|render a permitted embedded macro|deny attachment download after access removal"),
        m("access", "Permissions and Governance", "apply space-level access restrictions|apply page-level read restrictions|deny anonymous access to a private space|remove inherited group permissions|revoke a test API token|restrict public page links|audit a space permission change|deny privilege escalation by a contributor|export only authorized space content|remove a departing member's content access"),
    ]},
]


if __name__ == "__main__":
    for pack in PACKS:
        write_pack(pack)
        print(f"{pack['display']}: 1,000 synthetic cases across five modules")