export const testCases = [
  {
    "Test Case ID":"AZU-AKS-00001",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Validate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00002",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Validate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00003",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Reject Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00004",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Update Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00005",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Search Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00006",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Route Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00007",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"UI",
    "Scenario":"Approve Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00008",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Restore Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00009",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Edit Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00010",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Escalate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00011",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00012",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00013",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00014",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Search Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00015",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Validate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00016",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Clone Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00017",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Escalate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00018",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Clone Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00019",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Validate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00020",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00021",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00022",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Update Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00023",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Submit Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00024",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Update Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00025",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Clone Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00026",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Update Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00027",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Route Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00028",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Archive Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00029",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Search Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00030",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00031",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Clone Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00032",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Route Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00033",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00034",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Restore Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00035",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Search Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00036",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Submit Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00037",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Edit Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00038",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00039",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Create Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00040",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00041",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Approve Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00042",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Escalate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00043",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Regression",
    "Scenario":"Create Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00044",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Validate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00045",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Create Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00046",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Restore Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00047",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Regression",
    "Scenario":"Update Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00048",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Update Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00049",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Edit Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00050",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Clone Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00051",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Search Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00052",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Security",
    "Scenario":"Archive Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00053",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Approve Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00054",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Performance",
    "Scenario":"Restore Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00055",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Archive Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00056",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Create Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00057",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Clone Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00058",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Archive Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00059",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Approve Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00060",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Validate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00061",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Edit Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00062",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"UI",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00063",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Functional",
    "Scenario":"Edit Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00064",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Restore Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00065",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Search Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00066",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Clone Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00067",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Archive Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00068",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Functional",
    "Scenario":"Restore Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00069",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Validate Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00070",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Accessibility",
    "Scenario":"Approve Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00071",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Security",
    "Scenario":"Submit Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00072",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Reject Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00073",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Approve Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00074",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Security",
    "Scenario":"Route Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00075",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00076",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Reject Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00077",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Clone Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00078",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Archive Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00079",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Integration",
    "Scenario":"Create Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00080",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Integration",
    "Scenario":"Update Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00081",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Functional",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00082",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"UI",
    "Scenario":"Restore Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00083",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Reject Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00084",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Performance",
    "Scenario":"Route Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00085",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00086",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Performance",
    "Scenario":"Clone Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00087",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"DevOps",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Integration",
    "Scenario":"Approve Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00088",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Security",
    "Flow":"Provision -> Validate -> Monitor -> Remediate",
    "Test Type":"Accessibility",
    "Scenario":"Archive Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00089",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Platform",
    "Flow":"Create -> Protect -> Audit -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Search Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  },
  {
    "Test Case ID":"AZU-AKS-00090",
    "Product":"Azure",
    "Folder":"aks",
    "Capability":"aks",
    "Domain":"Data",
    "Flow":"Deploy -> Scale -> Observe -> Rollback",
    "Test Type":"Regression",
    "Scenario":"Delete Azure aks",
    "Preconditions":"Azure access and test data available",
    "Steps":"1. Open aks.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"service\": \"VM\", \"region\": \"eastus\", \"iam_role\": \"Tester\"}"
  }
];