export const testCases = [
  {
    "Test Case ID":"WEB-CHE-00001",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Delete WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00002",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Clone WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00003",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Escalate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00004",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00005",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00006",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Clone WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00007",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Escalate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00008",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Edit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00009",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Validate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00010",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00011",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Reject WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00012",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Clone WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00013",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Escalate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00014",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Escalate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00015",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Approve WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00016",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00017",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Delete WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00018",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Submit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00019",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00020",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Route WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00021",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Submit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00022",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Update WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00023",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Update WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00024",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00025",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Clone WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00026",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Validate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00027",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Edit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00028",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00029",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Clone WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00030",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00031",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Route WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00032",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Submit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00033",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Submit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00034",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Delete WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00035",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Route WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00036",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Reject WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00037",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Search WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00038",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Update WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00039",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Validate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00040",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Approve WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00041",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00042",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00043",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00044",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Delete WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00045",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00046",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Search WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00047",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Edit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00048",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Approve WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00049",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Delete WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00050",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Edit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00051",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Validate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00052",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00053",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Edit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00054",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00055",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Clone WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00056",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Reject WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00057",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Route WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00058",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Delete WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00059",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Route WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00060",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Validate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00061",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Search WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00062",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00063",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Reject WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00064",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00065",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00066",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Edit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00067",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Approve WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00068",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Update WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00069",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Clone WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00070",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Reject WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00071",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00072",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00073",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Escalate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00074",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Route WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00075",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Route WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00076",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Update WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00077",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00078",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Update WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00079",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Route WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00080",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Route WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00081",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Update WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00082",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00083",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00084",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00085",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00086",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00087",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Escalate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00088",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Search WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00089",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Update WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00090",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00091",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Create WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00092",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00093",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00094",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Approve WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00095",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Update WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00096",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Approve WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00097",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Clone WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00098",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00099",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Approve WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00100",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Approve WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00101",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00102",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Clone WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00103",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Delete WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00104",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00105",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00106",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Validate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00107",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Restore WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00108",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Validate WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00109",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Archive WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-CHE-00110",
    "Product":"WebApps",
    "Folder":"checkout",
    "Capability":"checkout",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Edit WebApps checkout",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open checkout.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  }
];