export const testCases = [
  {
    "Test Case ID":"AND-PAY-00001",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00002",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00003",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Update Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00004",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Restore Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00005",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Route Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00006",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Submit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00007",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Delete Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00008",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00009",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Edit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00010",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Submit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00011",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Accessibility",
    "Scenario":"Route Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00012",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Functional",
    "Scenario":"Archive Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00013",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Archive Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00014",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Update Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00015",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Update Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00016",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00017",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Create Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00018",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00019",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Submit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00020",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Edit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00021",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00022",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Reject Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00023",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Submit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00024",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Search Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00025",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00026",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Validate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00027",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Restore Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00028",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Accessibility",
    "Scenario":"Delete Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00029",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00030",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Edit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00031",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Archive Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00032",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Integration",
    "Scenario":"Create Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00033",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Restore Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00034",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Edit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00035",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Reject Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00036",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00037",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Edit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00038",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Reject Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00039",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Update Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00040",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"UI",
    "Scenario":"Clone Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00041",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00042",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Edit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00043",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00044",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Regression",
    "Scenario":"Route Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00045",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Reject Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00046",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Delete Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00047",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Route Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00048",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Route Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00049",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Archive Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00050",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Submit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00051",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Reject Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00052",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Search Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00053",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Security",
    "Scenario":"Archive Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00054",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00055",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Validate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00056",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Clone Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00057",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Create Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00058",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Clone Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00059",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Search Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00060",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Security",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00061",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Functional",
    "Scenario":"Search Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00062",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Route Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00063",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00064",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Search Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00065",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00066",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Submit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00067",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Regression",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00068",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Regression",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00069",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Reject Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00070",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Integration",
    "Scenario":"Reject Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00071",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Submit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00072",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Integration",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00073",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00074",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Reject Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00075",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Performance",
    "Scenario":"Update Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00076",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Submit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00077",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Submit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00078",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00079",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Search Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00080",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Validate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00081",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"UI",
    "Scenario":"Approve Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00082",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"UI",
    "Scenario":"Create Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00083",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Healthcare",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Security",
    "Scenario":"Update Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00084",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Integration",
    "Scenario":"Archive Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00085",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Search Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00086",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"UI",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00087",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00088",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Edit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00089",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Functional",
    "Scenario":"Validate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00090",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Update Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00091",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Functional",
    "Scenario":"Edit Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00092",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Security",
    "Scenario":"Route Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00093",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Archive Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00094",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Accessibility",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00095",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"FinTech",
    "Flow":"Launch -> Authenticate -> Use -> Logout",
    "Test Type":"Performance",
    "Scenario":"Escalate Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00096",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Offline -> Sync -> Resolve",
    "Test Type":"Performance",
    "Scenario":"Update Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00097",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Consumer",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Route Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00098",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Regression",
    "Scenario":"Route Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00099",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Push -> Open -> Verify",
    "Test Type":"Performance",
    "Scenario":"Archive Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  },
  {
    "Test Case ID":"AND-PAY-00100",
    "Product":"Android",
    "Folder":"payments",
    "Capability":"payments",
    "Domain":"Enterprise",
    "Flow":"Permission -> Action -> Persist",
    "Test Type":"Accessibility",
    "Scenario":"Reject Android payments",
    "Preconditions":"Android access and test data available",
    "Steps":"1. Open payments.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"device\": \"Pixel 9\", \"os\": \"Android 15\", \"network\": \"5G\"}"
  }
];