export const testCases = [
  {
    "Test Case ID":"WEB-FOR-00001",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00002",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00003",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00004",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00005",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Reject WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00006",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Edit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00007",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Update WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00008",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00009",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00010",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Archive WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00011",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00012",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Edit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00013",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Validate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00014",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00015",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00016",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Submit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00017",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Validate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00018",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Reject WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00019",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Search WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00020",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00021",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Search WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00022",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Delete WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00023",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Restore WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00024",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00025",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Route WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00026",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Search WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00027",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00028",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Delete WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00029",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00030",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00031",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Delete WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00032",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00033",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Route WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00034",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Submit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00035",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Archive WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00036",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Search WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00037",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00038",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Validate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00039",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Create WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00040",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00041",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Edit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00042",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Reject WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00043",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Reject WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00044",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Search WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00045",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Archive WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00046",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Restore WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00047",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Create WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00048",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Route WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00049",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Edit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00050",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Update WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00051",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00052",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Update WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00053",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00054",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Archive WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00055",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Archive WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00056",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Validate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00057",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Restore WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00058",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Edit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00059",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00060",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Submit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00061",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Validate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00062",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Archive WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00063",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Create WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00064",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00065",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Validate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00066",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Security",
    "Scenario":"Validate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00067",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00068",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Restore WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00069",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00070",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00071",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Regression",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00072",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Archive WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00073",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Delete WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00074",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Reject WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00075",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00076",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00077",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Regression",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00078",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00079",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00080",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Route WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00081",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Regression",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00082",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Create WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00083",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Update WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00084",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Security",
    "Scenario":"Validate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00085",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00086",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Archive WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00087",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00088",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Performance",
    "Scenario":"Edit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00089",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00090",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Accessibility",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00091",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Delete WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00092",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Edit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00093",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"UI",
    "Scenario":"Route WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00094",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Edit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00095",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Integration",
    "Scenario":"Create WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00096",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00097",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"SaaS",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Functional",
    "Scenario":"Escalate WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00098",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"UI",
    "Scenario":"Approve WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00099",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Security",
    "Scenario":"Clone WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00100",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Functional",
    "Scenario":"Reject WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00101",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Marketplace",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Performance",
    "Scenario":"Create WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00102",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Open -> Authenticate -> Use -> Close",
    "Test Type":"Performance",
    "Scenario":"Update WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00103",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Archive WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00104",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Integration",
    "Scenario":"Update WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00105",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Reject WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00106",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"Accessibility",
    "Scenario":"Route WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00107",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Functional",
    "Scenario":"Edit WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00108",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Route WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00109",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Retail",
    "Flow":"Render -> Interact -> Persist -> Report",
    "Test Type":"Integration",
    "Scenario":"Route WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  },
  {
    "Test Case ID":"WEB-FOR-00110",
    "Product":"WebApps",
    "Folder":"forms",
    "Capability":"forms",
    "Domain":"Media",
    "Flow":"Browse -> Add -> Checkout -> Confirm",
    "Test Type":"UI",
    "Scenario":"Delete WebApps forms",
    "Preconditions":"WebApps access and test data available",
    "Steps":"1. Open forms.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"browser\": \"Chrome\", \"viewport\": \"1440x900\", \"user\": \"demo\"}"
  }
];