export const testCases = [
  {
    "Test Case ID":"TOP-D36-00001",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Clone TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00002",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00003",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Edit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00004",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Approve TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00005",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Submit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00006",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Escalate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00007",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Edit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00008",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Update TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00009",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Create TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00010",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Update TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00011",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Create TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00012",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Create TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00013",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Route TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00014",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Restore TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00015",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Clone TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00016",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Escalate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00017",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Edit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00018",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Validate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00019",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Update TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00020",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Reject TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00021",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Submit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00022",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Delete TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00023",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Reject TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00024",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Validate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00025",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Delete TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00026",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Search TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00027",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Clone TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00028",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Escalate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00029",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Escalate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00030",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Route TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00031",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Restore TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00032",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Submit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00033",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Edit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00034",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Validate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00035",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Update TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00036",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Delete TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00037",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Reject TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00038",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Restore TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00039",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Approve TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00040",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Approve TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00041",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Search TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00042",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Reject TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00043",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Submit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00044",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Archive TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00045",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Edit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00046",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Route TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00047",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Reject TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00048",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Delete TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00049",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Reject TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00050",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Validate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00051",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Archive TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00052",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Clone TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00053",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Update TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00054",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Archive TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00055",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Submit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00056",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Regression",
    "Scenario":"Create TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00057",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Route TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00058",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Archive TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00059",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Performance",
    "Scenario":"Route TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00060",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"UI",
    "Scenario":"Clone TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00061",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Approve TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00062",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Search TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00063",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Escalate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00064",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Enterprise",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Approve TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00065",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Accessibility",
    "Scenario":"Restore TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00066",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Validate TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00067",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Security",
    "Scenario":"Delete TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00068",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Security",
    "Scenario":"Reject TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00069",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Functional",
    "Scenario":"Clone TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00070",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Reject TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00071",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Create TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00072",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Integration",
    "Scenario":"Submit TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00073",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Performance",
    "Scenario":"Search TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00074",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Functional",
    "Scenario":"Clone TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00075",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Update TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00076",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"ERP",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Accessibility",
    "Scenario":"Archive TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00077",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Clone TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00078",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"UI",
    "Scenario":"Clone TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Low",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00079",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"Life Sciences",
    "Flow":"Navigate -> Execute -> Validate -> Report",
    "Test Type":"Regression",
    "Scenario":"Search TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"High",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  },
  {
    "Test Case ID":"TOP-D36-00080",
    "Product":"TopProducts",
    "Folder":"d365",
    "Capability":"d365",
    "Domain":"CRM",
    "Flow":"Create -> Approve -> Close -> Audit",
    "Test Type":"Integration",
    "Scenario":"Approve TopProducts d365",
    "Preconditions":"TopProducts access and test data available",
    "Steps":"1. Open d365.\n2. Execute flow.\n3. Verify outcome.",
    "Expected Result":"Flow completes successfully",
    "Priority":"Medium",
    "Sample Data":"{\"suite\": \"Enterprise\", \"env\": \"QA\", \"locale\": \"en-US\"}"
  }
];